### PR TITLE
Remove advanced execution to increase nested call level

### LINKED ISSUE #455: Consider relaxing nested call limitation
Currently the limit is 5. 

Some complicated projects may need more. 

We should have a path for solution here.

### PR DESCRIPTION
**Pull request by taokayan**
Resolves #455 

removing the advanced execution for smart contract:

This can increse the stack size from around 20k to 46080, allowing around 19 levels (instead of 6) of nested contract calls.

test contract:
```
pragma solidity >=0.7.0 <0.9.0;

contract Recursion {

    uint256 public level;

    function callMe(uint256 n) public {
        if (n > level) {
            level = n;
        }
        if (n > 0) {
            Recursion(this).callMe(n - 1);
        }
    }
}
```

### CODE REVIEW

**Comment by elmato** [comment]
> can you create an pr in silkworm as well and only merge this one after the silkworm one is merged?

@taokayan can you also do that for evmone first?

**Comment by taokayan** [comment]
> > can you create an pr in silkworm as well and only merge this one after the silkworm one is merged?
> 
> @taokayan can you also do that for evmone first?
> 
> changes looks good

Done. Please also check https://github.com/eosnetworkfoundation/silkworm/pull/35 and https://github.com/eosnetworkfoundation/evmone/pull/2

**Comment by elmato** [comment]
> > > can you create an pr in silkworm as well and only merge this one after the silkworm one is merged?
> > 
> > 
> > @taokayan can you also do that for evmone first?
> > changes looks good
> 
> Done. Please also check [eosnetworkfoundation/silkworm#35](https://github.com/eosnetworkfoundation/silkworm/pull/35) and [eosnetworkfoundation/evmone#2](https://github.com/eosnetworkfoundation/evmone/pull/2)

Lets:
 - merge `evmone` [PR](https://github.com/eosnetworkfoundation/evmone/pull/2) first
 - update `evmone` sumodule in `silkworm` [PR](https://github.com/eosnetworkfoundation/silkworm/pull/35) (wait until its merged)
 - update `silkworm` silkworm submodule in this PR

**Comment by elmato** [comment]
silkworm submodule must point to https://github.com/eosnetworkfoundation/silkworm/commit/abc17386f9e2a962f9fc348e92fe636bcfde3ae0

**Review by elmato — APPROVED** [review]

**Pull request merged**
